// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyxg-ISwvcEPsgahYHNyrVhFTUMpKCavw',
    appId: '1:180998745651:web:76e6375be44f8aca7bfd46',
    messagingSenderId: '180998745651',
    projectId: 'ingredient-usage',
    authDomain: 'ingredient-usage.firebaseapp.com',
    storageBucket: 'ingredient-usage.firebasestorage.app',
    measurementId: 'G-0N7Z9XQLRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2pnTwwRflu4xAXgMjjdO6h8rJr8lCidU',
    appId: '1:180998745651:android:26c4e4f4b1e976ec7bfd46',
    messagingSenderId: '180998745651',
    projectId: 'ingredient-usage',
    storageBucket: 'ingredient-usage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXFxXAas_a20lcytF5qD4ZkOWQyyibEHM',
    appId: '1:180998745651:ios:cd7b72ea2ee5f12a7bfd46',
    messagingSenderId: '180998745651',
    projectId: 'ingredient-usage',
    storageBucket: 'ingredient-usage.firebasestorage.app',
    iosBundleId: 'com.example.ingredientUsageMonitoringSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXFxXAas_a20lcytF5qD4ZkOWQyyibEHM',
    appId: '1:180998745651:ios:cd7b72ea2ee5f12a7bfd46',
    messagingSenderId: '180998745651',
    projectId: 'ingredient-usage',
    storageBucket: 'ingredient-usage.firebasestorage.app',
    iosBundleId: 'com.example.ingredientUsageMonitoringSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyxg-ISwvcEPsgahYHNyrVhFTUMpKCavw',
    appId: '1:180998745651:web:4c6f618f27906a4a7bfd46',
    messagingSenderId: '180998745651',
    projectId: 'ingredient-usage',
    authDomain: 'ingredient-usage.firebaseapp.com',
    storageBucket: 'ingredient-usage.firebasestorage.app',
    measurementId: 'G-RG5558R3T4',
  );

}